version: 2

updates:

  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "composer"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "infrastructure"
